const currencyDetails = {
  aud: { code: 'aud', symbol: '$' },
  brl: { code: 'brl', symbol: '' },
  cad: { code: 'cad', symbol: '$' },
  chf: { code: 'chf', symbol: '' },
  clp: { code: 'clp', symbol: '' },
  cny: { code: 'cny', symbol: '' },
  czk: { code: 'czk', symbol: '' },
  dkk: { code: 'dkk', symbol: '' },
  eur: { code: 'eur', symbol: '' },
  gbp: { code: 'gbp', symbol: '' },
  hkd: { code: 'hkd', symbol: '' },
  huf: { code: 'huf', symbol: '' },
  idr: { code: 'idr', symbol: '' },
  ils: { code: 'ils', symbol: '' },
  inr: { code: 'inr', symbol: '' },
  jpy: { code: 'jpy', symbol: '' },
  krw: { code: 'krw', symbol: '' },
  mxn: { code: 'mxn', symbol: '' },
  myr: { code: 'myr', symbol: '' },
  nok: { code: 'nok', symbol: '' },
  nzd: { code: 'nzd', symbol: '$' },
  php: { code: 'php', symbol: '' },
  pkr: { code: 'pkr', symbol: '' },
  pln: { code: 'pln', symbol: '' },
  rub: { code: 'rub', symbol: '' },
  sek: { code: 'sek', symbol: '' },
  sgd: { code: 'sgd', symbol: '' },
  thb: { code: 'thb', symbol: '' },
  try: { code: 'try', symbol: '' },
  usd: { code: 'usd', symbol: '$' },
  vnd: { code: 'vnd', symbol: '' },
  twd: { code: 'twd', symbol: '' },
  zar: { code: 'zar', symbol: '' }
}

const currencies = [
  'aud',
  'brl',
  'cad',
  'chf',
  'clp',
  'cny',
  'czk',
  'dkk',
  'eur',
  'gbp',
  'hkd',
  'huf',
  'idr',
  'ils',
  'inr',
  'jpy',
  'krw',
  'mxn',
  'myr',
  'nok',
  'nzd',
  'php',
  'pkr',
  'pln',
  'rub',
  'sek',
  'sgd',
  'thb',
  'try',
  'usd',
  'vnd',
  'twd',
  'zar'
]

export default currencies
